version: '2'

services:
  tarantool:
    build: .
    networks:
      - tarantool
    ports:
      - "3301:3301"
    environment:
      - LUA_CPATH=/app/?.so

networks:
  tarantool:
    driver: bridge
